### ISSUE TITLE
Banner ad size and location

### ISSUE THREAD

**Issue by ta3usl** [cozycodegh/cordova-plugin-ads#1]
Hello,

Thank you for plugin. Verry easy and good plugin.

How can I change size and location for banner ads?

**Comment by cozycodegh** [comment]
Hi ta3usl, welcome. Right now the only banner position is at the bottom of the screen with the 320x50 banner size. It might be in a future release of the plugin

**Comment by cozycodegh** [comment]
See the banner document for setting the ad size and location:
https://github.com/cozycodegh/cordova-plugin-ads/blob/main/docs/banner.md
